### ISSUE TITLE
coredump  2.4.3-rocksdb-v5.13.4

### ISSUE THREAD

**Issue by FJSDS** [Tencent/Tendis#193]
## Description
coredump 

## Context
```
E0708 16:09:52.739351 13285 main.cpp:121] Failure:*** Aborted at 1657267792 (unix time) try "date -d @1657267792" if you are using GNU date ***
E0708 16:09:52.838970 13285 main.cpp:121] Failure:PC: @                0x0 (unknown)
E0708 16:09:52.839082 13285 main.cpp:121] Failure:*** SIGSEGV (@0x0) received by PID 13775 (TID 0x7fcc259ec700) from PID 0; stack trace: ***
E0708 16:09:52.840323 13285 main.cpp:121] Failure:    @     0x7fccb83e6630 (unknown)
E0708 16:09:52.865409 13285 main.cpp:121] Failure:    @           0x796623 tendisplus::RocksTxn::getKV()
E0708 16:09:52.869328 13285 main.cpp:121] Failure:    @           0x78fead tendisplus::RocksKVStore::getKV()
E0708 16:09:52.870607 13285 main.cpp:121] Failure:    @           0x510835 tendisplus::Command::delKey()
E0708 16:09:52.871389 13285 main.cpp:121] Failure:    @           0x5962ec _ZZN10tendisplus13UnlinkCommand3runB5cxx11EPNS_7SessionEENKUlS2_OSt6vectorINSt7__cxx1112basic_stringIcSt11char_t
raitsIcESaIcEEESaIS9_EEONS4_4listISt10unique_ptrINS_7KeyLockESt14default_deleteISF_EESaISI_EEEE_clES2_SC_SL_
E0708 16:09:52.871779 13285 main.cpp:121] Failure:    @           0xaeaa20 execute_native_thread_routine
E0708 16:09:52.872438 13285 main.cpp:121] Failure:    @     0x7fccb83deea5 start_thread
E0708 16:09:52.873323 13285 main.cpp:121] Failure:    @     0x7fccb7bfdb0d __clone
E0708 16:09:52.873983 13285 main.cpp:121] Failure:    @                0x0 (unknown)

```
```  coredump info
Core was generated by `./tendis-2/bin/tendisplus tendis-2/tendisplus.conf'.
Program terminated with signal 11, Segmentation fault.
#0  tendisplus::RocksTxn::getKV (this=this@entry=0x7fcc4e001000, key=...)
    at /data/tendis_bin/workspace/tendisplus-master-release/pipeline_347/tendisplus/src/tendisplus/storage/rocks/rocks_kvstore.cpp:391
391	/data/tendis_bin/workspace/tendisplus-master-release/pipeline_347/tendisplus/src/tendisplus/storage/rocks/rocks_kvstore.cpp: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64
(gdb) bt
#0  tendisplus::RocksTxn::getKV (this=this@entry=0x7fcc4e001000, key=...)
    at /data/tendis_bin/workspace/tendisplus-master-release/pipeline_347/tendisplus/src/tendisplus/storage/rocks/rocks_kvstore.cpp:391
#1  0x000000000078fead in tendisplus::RocksKVStore::getKV (this=<optimized out>, key=..., txn=0x7fcc4e001000)
    at /data/tendis_bin/workspace/tendisplus-master-release/pipeline_347/tendisplus/src/tendisplus/storage/rocks/rocks_kvstore.cpp:2410
#2  0x0000000000510835 in tendisplus::Command::delKey (sess=sess@entry=0x7fcc812e8f50, key=..., tp=tp@entry=tendisplus::RT_DATA_META, txn=0x7fcc4e001000)
    at /data/tendis_bin/workspace/tendisplus-master-release/pipeline_347/tendisplus/src/tendisplus/commands/command.cpp:725
#3  0x00000000005962ec in tendisplus::UnlinkCommand::run[abi:cxx11](tendisplus::Session*)::{lambda(tendisplus::Session*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&, std::__cxx11::list<std::unique_ptr<tendisplus::KeyLock, std::default_delete<tendisplus::KeyLock> >, std::allocator<std::unique_ptr<tendisplus::KeyLock, std::default_delete<tendisplus::KeyLock> > > >&&)#1}::operator()(tendisplus::Session*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&, std::__cxx11::list<std::unique_ptr<tendisplus::KeyLock, std::default_delete<tendisplus::KeyLock> >, std::allocator<std::unique_ptr<tendisplus::KeyLock, std::default_delete<tendisplus::KeyLock> > > >&&) const (__closure=<optimized out>, sess=0x7fcc812e8f50, keys=<unknown type in /root/tendis/tendis-2/bin/tendisplus, CU 0xaf3a27, DIE 0xbca65a>, locklist=<optimized out>)
    at /data/tendis_bin/workspace/tendisplus-master-release/pipeline_347/tendisplus/src/tendisplus/commands/del.cpp:161
#4  0x0000000000aeaa20 in std::execute_native_thread_routine (__p=<optimized out>) at ../../../.././libstdc++-v3/src/c++11/thread.cc:84
#5  0x00007fccb83deea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fccb7bfdb0d in clone () from /lib64/libc.so.6

```

## Your Environment
centos 7

**Comment by raffertyyu** [comment]
非常感谢反馈，可以分享一下coredump文件或者复现方法嘛。如果可以的话，能否加我微信raffertyyu进一步跟进一下。
