### ISSUE TITLE
通过jedis客户端连接报错：redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.

### ISSUE THREAD

**Issue by Klay-Zh** [Tencent/Tendis#261]
根据示例代码连接不上：
    public static void main(String[] args) {
        try {
            /**以下参数分别填写您的 Tendis 实例内网 IP、端口号、实例 ID 和密码*/
            String host = "192.168.209.***";
            int port = 51002;
            //连接 Tendis
            Jedis jedis = new Jedis(host, port);

            /**接下来可以开始操作 Tendis 实例，可以参考 https://github.com/xetorthio/jedis */
            //设置 Key
            jedis.set("redis", "tencent");
            //获取 Key
            String value = jedis.get("redis");
            System.out.println("get key redis is: " + value);

            //关闭退出
            jedis.quit();
            jedis.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

执行报错：
redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:110)
	at redis.clients.jedis.Connection.connect(Connection.java:226)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:140)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:163)
	at redis.clients.jedis.BinaryClient.set(BinaryClient.java:199)
	at redis.clients.jedis.Client.set(Client.java:85)
	at redis.clients.jedis.Jedis.set(Jedis.java:226)
	at com.jpush.yu.message.HelloRedis.main(HelloRedis.java:18)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:80)
	... 7 more

**Comment by raffertyyu** [comment]
我本地测试没有这个问题。有复现步骤或者更多错误信息吗。
